# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'horizons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from gui.uis.windows.screens2.common import formatDate, parseDate
from qt_core import *


horizons_default_input = {
    "Start Date": "2022-01-01",
    "End Date": "2022-01-01",
    "Granularity": 1,
    "Periodicity": {
        "Type": "Year",
        "On": 1,
        "Off": 2
    },
    "Historic Sample Years": []
}


class Ui_Horizons(QObject):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Horizon")
        Dialog.resize(900, 600)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.endDateLabel = QLabel(Dialog)
        self.endDateLabel.setObjectName("endDateLabel")
        self.formLayout_3.setWidget(1, QFormLayout.LabelRole, self.endDateLabel)
        self.endDateDateEdit = QDateEdit(Dialog)
        self.endDateDateEdit.setObjectName("endDateDateEdit")
        self.formLayout_3.setWidget(1, QFormLayout.FieldRole, self.endDateDateEdit)
        self.startDateLabel = QLabel(Dialog)
        self.startDateLabel.setObjectName("startDateLabel")
        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.startDateLabel)
        self.startDateDateEdit = QDateEdit(Dialog)
        self.startDateDateEdit.setObjectName("startDateDateEdit")
        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.startDateDateEdit)
        self.granularityLabel = QLabel(Dialog)
        self.granularityLabel.setObjectName("granularityLabel")
        self.formLayout_3.setWidget(2, QFormLayout.LabelRole, self.granularityLabel)
        self.granularitySpinBox = QSpinBox(Dialog)
        self.granularitySpinBox.setObjectName("granularitySpinBox")
        self.granularitySpinBox.setMaximum(10000)
        self.formLayout_3.setWidget(2, QFormLayout.FieldRole, self.granularitySpinBox)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.periodicityGroupBox = QGroupBox(Dialog)
        self.periodicityGroupBox.setObjectName("periodicityGroupBox")
        self.verticalLayout_2 = QVBoxLayout(self.periodicityGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.typeLabel = QLabel(self.periodicityGroupBox)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.typeLabel)
        self.typeComboBox = QComboBox(self.periodicityGroupBox)
        self.typeComboBox.setObjectName("typeComboBox")
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.typeComboBox)
        self.onLabel = QLabel(self.periodicityGroupBox)
        self.onLabel.setObjectName("onLabel")
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.onLabel)
        self.onSpinBox = QSpinBox(self.periodicityGroupBox)
        self.onSpinBox.setObjectName("onSpinBox")
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.onSpinBox)
        self.offLabel = QLabel(self.periodicityGroupBox)
        self.offLabel.setObjectName("offLabel")
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.offLabel)
        self.offSpinBox = QSpinBox(self.periodicityGroupBox)
        self.offSpinBox.setObjectName("offSpinBox")
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.offSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.periodicityGroupBox)
        self.historicSampleYearsGroupBox = QGroupBox(Dialog)
        self.historicSampleYearsGroupBox.setObjectName("historicSampleYearsGroupBox")
        self.verticalLayout_3 = QVBoxLayout(self.historicSampleYearsGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.historicSampleYearsListView = QListView(self.historicSampleYearsGroupBox)
        self.historicSampleYearsListView.setObjectName("historicSampleYearsListView")
        self.historicSampleYearsModel = QStandardItemModel()
        self.historicSampleYearsListView.setModel(self.historicSampleYearsModel)
        self.verticalLayout_3.addWidget(self.historicSampleYearsListView)
        self.verticalLayout.addWidget(self.historicSampleYearsGroupBox)

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Horizons"))
        self.endDateLabel.setText(_translate("Dialog", "End Date"))
        self.startDateLabel.setText(_translate("Dialog", "Start Date"))
        self.granularityLabel.setText(_translate("Dialog", "Granularity"))
        self.periodicityGroupBox.setTitle(_translate("Dialog", "Periodicity"))
        self.typeLabel.setText(_translate("Dialog", "Type"))
        self.onLabel.setText(_translate("Dialog", "On"))
        self.offLabel.setText(_translate("Dialog", "Off"))
        self.historicSampleYearsGroupBox.setTitle(_translate("Dialog", "Historic Sample Years"))
    
    def setChoices(self, options):
        self.typeComboBox.clear()
        self.typeComboBox.addItems(options["Periodicities"])

        self.historicSampleYearsModel.clear()
        for year in options["Years"]:
            item = QStandardItem(str(year))
            item.setCheckable(True)
            self.historicSampleYearsModel.appendRow(item)
    
    def setInput(self, input):
        self.input = input
        self.startDateDateEdit.setDate(parseDate(self.input["Start Date"]))
        self.endDateDateEdit.setDate(parseDate(self.input["End Date"]))
        self.granularitySpinBox.setValue(self.input["Granularity"])
        self.typeComboBox.setCurrentText(self.input["Periodicity"]["Type"])
        self.onSpinBox.setValue(self.input["Periodicity"]["On"])
        self.offSpinBox.setValue(self.input["Periodicity"]["Off"])
        for i in range(self.historicSampleYearsModel.rowCount()):
            item = self.historicSampleYearsModel.item(i, 0)
            if item.text() in self.input["Historic Sample Years"]:
                item.setCheckState(Qt.Checked)
            else:
                item.setCheckState(Qt.Unchecked)
    
    def getOutput(self):
        years = []
        for i in range(self.historicSampleYearsModel.rowCount()):
            item = self.historicSampleYearsModel.item(i, 0)
            if item.checkState() == Qt.Checked:
                years.append(item.text())

        output = {
            "Start Date": formatDate(self.startDateDateEdit.date()),
            "End Date": formatDate(self.endDateDateEdit.date()),
            "Granularity": self.granularitySpinBox.value(),
            "Periodicity": {
                "Type": self.typeComboBox.currentText(),
                "On": self.onSpinBox.value(),
                "Off": self.offSpinBox.value()
            },
            "Historic Sample Years": years
        }
        return output