# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qt_core import *


class Ui_OpenModelDialog(object):
    def setupUi(self, OpenModelDialog):
        OpenModelDialog.setObjectName("OpenModelDialog")
        OpenModelDialog.resize(736, 482)
        self.verticalLayout_2 = QVBoxLayout(OpenModelDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QLabel(OpenModelDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.modelList = QListView(OpenModelDialog)
        self.modelList.setObjectName("modelList")
        self.verticalLayout.addWidget(self.modelList)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QLabel(OpenModelDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.versionList = QListView(OpenModelDialog)
        self.versionList.setObjectName("versionList")
        self.verticalLayout_3.addWidget(self.versionList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.buttonBox = QDialogButtonBox(OpenModelDialog)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(OpenModelDialog)
        self.buttonBox.accepted.connect(OpenModelDialog.accept)
        self.buttonBox.rejected.connect(OpenModelDialog.reject)
        QMetaObject.connectSlotsByName(OpenModelDialog)

    def retranslateUi(self, OpenModelDialog):
        _translate = QCoreApplication.translate
        OpenModelDialog.setWindowTitle(_translate("OpenModelDialog", "Open Model"))
        self.label.setText(_translate("OpenModelDialog", "Models"))
        self.label_2.setText(_translate("OpenModelDialog", "History"))
